### ISSUE TITLE
Getting a problem from just the beginning of the lesson: npm install && npm start

### ISSUE THREAD

**Issue by WilliamMena** [learn-co-students/react-create-element-v-000#8]
Not sure where to enter a start script or what to do from here but I can't even start the lesson. The log that it is giving me is shown at the bottom.

// ♥ npm install && npm start
up to date in 0.403s
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/WilliamMena1/.npm/_logs/2017-08-09T17_23_52_731Z-debug.log

// ♥ node -v
v8.2.1

// ♥ npm -v
5.3.0

THIS IS THE LOG FILE I  GET AFTER TRYING 'npm install && npm start'

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.2.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose stack Error: missing script: start
4 verbose stack     at run (/usr/local/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /usr/local/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:114:5
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:401:5
4 verbose stack     at handleExists (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:365:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
5 verbose cwd /usr/local/lib/node_modules/create-react-app
6 verbose Darwin 15.6.0
7 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "start"
8 verbose node v8.2.1
9 verbose npm  v5.3.0
10 error missing script: start
11 verbose exit [ 1, true ]

**Comment by WilliamMena** [comment]
I also got this after uninstalling and reinstalling node, npm and react. Before this I couldn't even get to this section of being able to press 'npm install && npm start'

**Comment by WilliamMena** [comment]
[13:26:16] ~
// ♥ npm install -g create-react-app webpack
/usr/local/bin/create-react-app -> /usr/local/lib/node_modules/create-react-app/index.js
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
+ create-react-app@1.4.0
+ webpack@3.5.2
updated 2 packages in 7.158s
[13:26:31] ~
// ♥ npm install && npm start
npm WARN saveError ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm WARN WilliamMena1 No description
npm WARN WilliamMena1 No repository field.
npm WARN WilliamMena1 No README data
npm WARN WilliamMena1 No license field.

up to date in 0.071s
npm ERR! path /Users/WilliamMena1/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/WilliamMena1/.npm/_logs/2017-08-09T17_26_59_737Z-debug.log
[13:26:59] ~
// ♥ cd /usr/local/lib/node_modules/create-react-app
[13:27:11] create-react-app
// ♥ npm install && npm start
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.355s
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/WilliamMena1/.npm/_logs/2017-08-09T17_27_15_406Z-debug.log

**Comment by WilliamMena** [comment]
`[13:26:16] ~
// ♥ npm install -g create-react-app webpack
/usr/local/bin/create-react-app -> /usr/local/lib/node_modules/create-react-app/index.js
/usr/local/bin/webpack -> /usr/local/lib/node_modules/webpack/bin/webpack.js
+ create-react-app@1.4.0
+ webpack@3.5.2
updated 2 packages in 7.158s
[13:26:31] ~
// ♥ npm install && npm start
npm WARN saveError ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm WARN WilliamMena1 No description
npm WARN WilliamMena1 No repository field.
npm WARN WilliamMena1 No README data
npm WARN WilliamMena1 No license field.

up to date in 0.071s
npm ERR! path /Users/WilliamMena1/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/WilliamMena1/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/WilliamMena1/.npm/_logs/2017-08-09T17_26_59_737Z-debug.log
[13:26:59] ~
// ♥ cd /usr/local/lib/node_modules/create-react-app
[13:27:11] create-react-app
// ♥ npm install && npm start
npm notice created a lockfile as package-lock.json. You should commit this file.
up to date in 0.355s
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/WilliamMena1/.npm/_logs/2017-08-09T17_27_15_406Z-debug.log
`
